language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.2

env:
  - RAILS_VERSION="4.0"
  - RAILS_VERSION="4.1"
  - RAILS_VERSION="4.2"

matrix:
  allow_failures:
    - RAILS_VERSION="4.1"
    - RAILS_VERSION="4.2"

script: bundle exec rake

notifications:
  email: false
